version: '3.3'
services:
  redis1:
    image: redis:4.0.2
    container_name: redis1
    ports:
      - "6379:6379"
    command: redis-server --slaveof redis-sentinel1 26379
    networks:
      - redis-net
    restart: always

  redis2:
    image: redis:4.0.2
    container_name: redis2
    ports:
      - "6380:6379"
    command: redis-server --slaveof redis-sentinel2 26379
    networks:
      - redis-net
    restart: always

  redis3:
    image: redis:4.0.2
    container_name: redis3
    ports:
      - "6381:6379"
    command: redis-server --slaveof redis-sentinel3 26379
    networks:
      - redis-net
    restart: always

  redis-sentinel1:
    image: redis:4.0.2
    container_name: redis-sentinel1
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
      - "26379:26379"
    networks:
      - redis-net
    restart: always

  redis-sentinel2:
    image: redis:4.0.2
    container_name: redis-sentinel2
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
      - "26380:26379"
    networks:
      - redis-net
    restart: always

  redis-sentinel3:
    image: redis:4.0.2
    container_name: redis-sentinel3
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
      - "26381:26379"
    networks:
      - redis-net
    restart: always

networks:
  redis-net:
